### ISSUE TITLE
Add icon for kanban

### ISSUE THREAD

**Issue by hunvreus** [Wiredcraft/fullpm-chrome#3]
Currently, when displaying the Kanban menu item, we don't have an icon like other links have. I would like to add  an icon, designed in the same style with the same color as the other items, that looks more or less like the Trello icon.

Also, we need to figure out how they change the color of the icon; are they simply switching the icon or using some kind of JS magic.

The icon will be SVG for now, and we'll dump the code directly in the extension (like GitHub does). For example:

```
<a href="/Wiredcraft/fullpm-chrome/wiki" class="js-selected-navigation-item reponav-item" data-hotkey="g w" data-selected-links="repo_wiki /Wiredcraft/fullpm-chrome/wiki">
      <svg aria-hidden="true" class="octicon octicon-book" height="16" version="1.1" viewBox="0 0 16 16" width="16"><path d="M3 5h4v1H3V5zm0 3h4V7H3v1zm0 2h4V9H3v1zm11-5h-4v1h4V5zm0 2h-4v1h4V7zm0 2h-4v1h4V9zm2-6v9c0 .55-.45 1-1 1H9.5l-1 1-1-1H2c-.55 0-1-.45-1-1V3c0-.55.45-1 1-1h5.5l1 1 1-1H15c.55 0 1 .45 1 1zm-8 .5L7.5 3H2v9h6V3.5zm7-.5H9.5l-.5.5V12h6V3z"></path></svg>
      Wiki
</a>
```

**Comment by hopechen1028** [comment]
@hunvreus 
[kanban-icon.zip](https://github.com/Wiredcraft/fullpm-chrome/files/410314/kanban-icon.zip)

**Comment by hunvreus** [comment]
@hopechen1028 we need to:
1. Get a version for hover with a `#111` fill,
2. Ensure we're designing it for a 16x16 canvas,
3. Get both versions as a merged path. If you look at the code of the icons for the other tabs on GitHub (notice the single `path` object in the middle);
   
   ```
   <svg aria-hidden="true" class="octicon octicon-book" height="16" version="1.1" viewBox="0 0 16 16" width="16"><path d="M3 5h4v1H3V5zm0 3h4V7H3v1zm0 2h4V9H3v1zm11-5h-4v1h4V5zm0 2h-4v1h4V7zm0 2h-4v1h4V9zm2-6v9c0 .55-.45 1-1 1H9.5l-1 1-1-1H2c-.55 0-1-.45-1-1V3c0-.55.45-1 1-1h5.5l1 1 1-1H15c.55 0 1 .45 1 1zm-8 .5L7.5 3H2v9h6V3.5zm7-.5H9.5l-.5.5V12h6V3z"></path></svg>
   ```

**Comment by hunvreus** [comment]
Done. FYI @hopechen1028 it still wasn't working, mostly because exporting shapes with borders in Sketch (and/or Illustrator) tend to result in the entire shape being printed rather than just the border.
